apiVersion: apps/v1
kind: Deployment
metadata:
  name: drety
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drety
  template:
    metadata:
      labels:
        app: drety
    spec:
      containers:
      - image: okteto.dev/drety:latest
        name: drety
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "bd9fefd0-4ef3-013d-e124-c8d59621c648"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "bd9fefd0-4ef3-013d-e124-c8d59621c648"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
